### ISSUE TITLE
LLVM/Clang Support for Linux

### ISSUE THREAD

**Issue by Congyuwang** [messense/maturin-action#12]
I tried to build a Maturin project on linux platform, but I got this error message: "libclang.so, libclang.so.*, ...." not found.

It seems that the manylinux docker image does not have clang/llvm installed.

So, I set `container: off`, but it can't build manylinux wheel, and the error is 'linux_x86_64' wheel can't be uploaded.

Is there any way that I can build a manylinux wheel for this Maturin Project with Clang using Github Workflow?

Thanks.

**Comment by messense** [comment]
There isn't currently any hook to install libraries before running maturin, however you can use a customized docker image by supply it to the `container` argument.

**Comment by messense** [comment]
Added cmake in https://github.com/messense/manylinux-cross/commit/bb10dff23946f32c4dc401ade0845163ee827f5a
