### ISSUE TITLE
Disallow `--universal2` option for mac on Python 3.6 / 3.7

### ISSUE THREAD

**Issue by davidhewitt** [messense/maturin-action#13]
Sounds like users might be accidentally making invalid builds doing this:
https://github.com/PyO3/pyo3/issues/1911
https://github.com/milesgranger/pyrus-cramjam/pull/62#issuecomment-878799144

**Comment by Congyuwang** [comment]
Building with `--universal2` flag on Python 3.6.13 on my laptop works. I guess the problem is related to newer version, perhaps?
