### ISSUE TITLE
Install system libraries

### ISSUE THREAD

**Issue by kchaliki** [messense/maturin-action#14]
Hopefully this is an easy one. I would like to apt-get install a bunch of libraries before starting a build in a 2_24 container, is that a bad idea and if not, how do I go about it? I assume just running the command before the maturin-action step will not affect the container the build itself happens in?

**Comment by messense** [comment]
You can use a customized docker image by supply it to the `container` argument.

**Comment by kchaliki** [comment]
Thanks @messense, in the end I found that it doesn't look like the version of clang I am trying to import is supported by any of the existing manylinux containers so I resorted to "cheating" and using rust_setuptools & auditwheel manually to force the creation of a "manylinux" wheel which is of course not a real one
