### ISSUE TITLE
maturin-action only builds wheel for one Python version on macOS (and not all installed)

### ISSUE THREAD

**Issue by EwoutH** [messense/maturin-action#15]
I'm trying to build wheels for multiple Python version in one run. On Linux and Windows this works perfect, but on macOS it only finds a single Python version, while four Python versions (six including PyPy) [are installed](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#python). For macOS, I'm trying to build universal wheels for x86-64 and Apple Silicon using `--universal2`.

- [Workflow file](https://github.com/hugoledoux/startinpy/blob/2f149851e9d2dd74064ebe16c440c35d042203a6/.github/workflows/build.yml)
- [GitHub Actions run](https://github.com/hugoledoux/startinpy/actions/runs/1450974818)

Windows Server 2019
```
🐍 Found CPython 3.10 at C:\hostedtoolcache\windows\Python\3.10.0\x64\python.exe, CPython 3.9 at C:\hostedtoolcache\windows\Python\3.9.8\x64\python.exe, CPython 3.8 at C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe, CPython 3.7 at C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
```

Ubuntu 20.04 (with `manylinux: auto`)
```
`Found CPython 3.7m at python3.7, CPython 3.8 at python3.8, CPython 3.9 at python3.9, CPython 3.10 at python3.10, PyPy 3.7 at pypy3.7
```

macOS 11 (with `--universal2`)
```
Found CPython 3.9 at python3.9
```

**Comment by messense** [comment]
Does it finds more Python interpreters without `--universal2`? It could be that [installed](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-11-Readme.md#python) python versions aren't in `PATH`, can you try [setup-python](https://github.com/actions/setup-python) action before maturin-action?

**Comment by messense** [comment]
There Python versions are **cached** thus not in `PATH` by default, see https://github.community/t/what-are-cached-tools/140010 , looks like you should use setup-python action before maturin-action.

**Comment by messense** [comment]
Actually I think we can also add them to `PATH` automatically on our end.

**Comment by EwoutH** [comment]
Thanks for considering this! It saves a lot of code, which can get quite complicated with different build matrices.

**Comment by Mr-Milk** [comment]
I'm still having this issue in the latest build, maturin use the cached py3.9 instead of the one set by `setup-python`
![image](https://user-images.githubusercontent.com/23433306/141892556-7b3ea5ea-0ab8-4958-a59e-631a7bda5911.png)

**Comment by messense** [comment]
@Mr-Milk Use `-i pythonX.Y` option.

**Comment by messense** [comment]
@Mr-Milk Can you try `messense/maturin-action@setup-python`?

**Comment by Mr-Milk** [comment]
I tried the `-i pythonX.Y` it works. The python version in the later actions becomes the cached 3.9, I will try `messense/maturin-action@setup-python`.

**Comment by Mr-Milk** [comment]
It worked!😃
Are you going to make a new release? Should I set it back to messense/maturin-action@v1?

**Comment by messense** [comment]
Released, v1 updated.

**Comment by EwoutH** [comment]
To build on this, would it be possible to add path detection for PyPy on all images? PyPy 3.7 and 3.8 are pre-installed on all [virtual environments](https://github.com/actions/virtual-environments).

**Comment by messense** [comment]
> To build on this, would it be possible to add path detection for PyPy on all images? PyPy 3.7 and 3.8 are pre-installed on all [virtual environments](https://github.com/actions/virtual-environments).

Actually I've tried adding PyPy but it gets weird so I removed it.

https://github.com/messense/maturin-action/runs/4196117054?check_suite_focus=true

```
🔗 Found pyo3 bindings
🐍 Found PyPy 3.7 at python3.7, PyPy 3.8 at python3.8, CPython 3.9 at python3.9, CPython 3.10 at python3.10, PyPy 3.7 at pypy3.7
```
