### ISSUE TITLE
Example using maturin publish or maturin upload with a pypi token

### ISSUE THREAD

**Issue by konstin** [messense/maturin-action#21]
Currently, all examples use twine for the pypi upload instead of maturin publish. It would be cool to have an example with maturin publish or maturin upload that uses a pypi token similar to https://github.com/entity-neural-network/ragged-buffer/blob/78657b4603d8dc9680e3d166064f73b289aa2ac1/.github/workflows/publish-wheel.yaml#L52-L59

**Comment by messense** [comment]
👍

We should also update the `maturin new`'s template to use it too: https://github.com/PyO3/maturin/blob/fa66292d3c2a29389bbfa24c54820db5b5d4a5c8/src/templates/CI.yml.j2#L63-L69

**Comment by messense** [comment]
An example is modified to use maturin: https://github.com/messense/rjmespath-py/blob/59ba98e1d0e366681713290f70f2db705bb31d79/.github/workflows/CI.yml#L159-L165
