### ISSUE TITLE
error: could not find native static library `python3.8`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by 007vasy** [messense/maturin-action#32]
action fails on the newer code in github action 

(build works both on ubuntu 20.04 and mac m1 locally)

https://github.com/007vasy/solana-bigtable-decode/compare/99a2f1667e06f9d812dfb5e2d9d5f8e9c7af9864..e9383e702f8c2bb033b5a168a4ec1da6aa24f6ad

full error message

`error: could not find native static library `python3.8`, perhaps an -L flag is missing?

error: aborting due to previous error

error: could not compile `python3-sys` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
error: build failed
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `cargo rustc --manifest-path Cargo.toml --message-format json --release --lib --`
Error: The process '/usr/bin/docker' failed with exit code 1`

**Comment by 007vasy** [comment]
@messense do you have any idea what could cause the issue? (or how could we solve it?)

**Comment by messense** [comment]
Remove the cpython dependency.

https://github.com/007vasy/solana-bigtable-decode/blob/49a17ddf6295c80ce6aca3894ab33acad554cd4a/Cargo.toml#L22
