### ISSUE TITLE
Parse toolchain seems wrong?

### ISSUE THREAD

**Issue by Mr-Milk** [messense/maturin-action#50]
Hi there, latest few builds of my CI failed with similar message:
```error: Pre-checks for host and toolchain failed: invalid toolchain name: '[toolchain]'``` (Linux)

Judge from other other output the toolchain value is not parse correctly, they all display `[toolchain]`

I also tried with previous v1.27.0 and everything works fine.

**Comment by messense** [comment]
If you are using toml, you should rename your `rust-toolchain` file to `rust-toolchain.toml`

**Comment by Mr-Milk** [comment]
Yeah, that works! Thanks so much!
