### ISSUE TITLE
default to maturin 0.13.0 (and maybe allow specifying a Python version?)

### ISSUE THREAD

**Issue by jmhodges** [messense/maturin-action#55]
maturin 0.13.0 came out today which is great and exciting!

It would be cool for maturin-action to use it. I see there's some infra for bumping the version but I'm not sure how it's meant to be used or I'd produce a PR myself!

Using `maturin-version: 0.13.0`, however, seems to fail in my CI runs because PyO3 has dropped their support for Python 3.6 while something in maturin-action is attempting to run on it. For example, this [failed CI run](https://github.com/jmhodges/biscuit-auth-python/runs/7267106433?check_suite_focus=true) says:

```
 error: the configured Python interpreter version (3.6) is lower than PyO3's minimum supported version (3.7)
```

There doesn't seem to be to adjust the Python interpreter version, either. I've changed my own `pyproject.toml` to require a Python version `>=3.7`, but that wasn't the trick.

Thanks so much for this software!

**Comment by jmhodges** [comment]
(My CI tasks are based on the output of the 0.13.0 `maturin init` CI.yml)

**Comment by messense** [comment]
I think the problem is that the manylinux2010 docker image's `python3` is `python3.6` so it's affected by https://maturin.rs/migration.html#only-build-wheels-for-current-python-interpreter-in-path-by-default.

I think what you want is the new `--find-interpreter` option.

**Comment by messense** [comment]
And if you just want to specify some python versions, you always do that with `args: --release -o dist -i 3.7 3.8 3.9 3.10`.
