### ISSUE TITLE
sdist not built

### ISSUE THREAD

**Issue by samuelcolvin** [messense/maturin-action#58]
We've just had a problem on watchfiles where we forgot to include source distributions. https://github.com/samuelcolvin/watchfiles/issues/175

I'm not sure what changed between v0.15 and v0.16, could it have been something to do with maturin/maturin-action?

This issue is just an alert in case others have encountered the same problem, I've fixed this in watchfiles, see https://github.com/samuelcolvin/watchfiles/pull/176.

Feel free to close the issue.

**Comment by messense** [comment]
Right, it's the [changed behavior in maturin 0.13.0](https://maturin.rs/migration.html#source-distributions-are-not-built-by-default), https://github.com/samuelcolvin/watchfiles/pull/176 is the correct fix.

**Comment by samuelcolvin** [comment]
thanks, sorry for noise.
