### ISSUE TITLE
`rust-toolchain` file currently takes priority over the action input

### ISSUE THREAD

**Issue by samuelcolvin** [messense/maturin-action#64]
As per

https://github.com/messense/maturin-action/blob/5ee8aeab26c4261858746978295a2fee8f8f54c7/src/index.ts#L178-L198

Currently a `rust-toolchain.toml` or `rust-toolchain` file takes priority over setting the `rust-toolchain` input.

I think the action input should win if both are present

**Comment by samuelcolvin** [comment]
ha, I was just about to submit a PR.

Thanks so much.

**Comment by samuelcolvin** [comment]
Will you make a new release, or should I use `main`?

**Comment by messense** [comment]
I'll release it into `v1` once CI passed.

**Comment by messense** [comment]
> I'll release it into `v1` once CI passed.

Done.
