### ISSUE TITLE
add support for passing custom environment variables to docker

### ISSUE THREAD

**Issue by louneskmt** [messense/maturin-action#69]
Some crates need the use of specific environment variables (for example [`prost-build`](https://docs.rs/prost-build/latest/prost_build/#sourcing-protoc)). Currently, only the ones starting with `CARGO_`, `RUST`, `MATURIN_` and `PYO3_` are passed to the Docker image.

**Comment by messense** [comment]
The `prost-build` example isn't really useful, because we don't have `protoc` installed in ours docker images, passing `PROTOC` won't work.

If you are using a customized `Dockerfile`, you can just set env vars in `Dockerfile`.

**Comment by louneskmt** [comment]
I was building protoc and moving the binary to the work directory (automatically mounted into the container). 

In the end, I added a job to build the proto files beforehand. Thanks anyway!
