### ISSUE TITLE
Question: Is RUSTFLAGS picked up by `maturin-action`

### ISSUE THREAD

**Issue by ritchie46** [messense/maturin-action#70]
Sorry for this trivial question, but I could not find a way to verifiy that.

Does a shell step like this.

```
      - name: Prepare maturin publish
        shell: bash
        run: |
          export RUSTFLAGS='-C target-feature=+fxsr,+sse,+sse2,+sse3,+ssse3,+sse4.1,+sse4.2,+popcnt,+avx,+fma'
```

Ensure that those `RUSTFLAGS` are used by the `maturin-action` step later?

**Comment by messense** [comment]
It should, see https://github.com/messense/maturin-action/blob/bd989f80e15dc92c377222571a34b19fbe35f41b/src/index.ts#L502-L513

**Comment by messense** [comment]
![image](https://user-images.githubusercontent.com/1556054/185869205-0eb123f7-5eac-4097-9dce-23676cdcba1d.png)

You can verify it in the build log.

**Comment by ritchie46** [comment]
Then it doesn't seem to do that. :thinking: 

![image](https://user-images.githubusercontent.com/3023000/185871115-8b2f7cdb-76c7-4426-92f5-ba3db9a76d58.png)

**Comment by ritchie46** [comment]
Yep, that worked. :)

![image](https://user-images.githubusercontent.com/3023000/185873925-09b263a3-7f50-40b8-9c13-0b38bf16aaf6.png)
