### ISSUE TITLE
ppc64le naming is wrong?

### ISSUE THREAD

**Issue by milesgranger** [messense/maturin-action#8]
Hi!

Thanks again for putting this together, I've recently made a release with the new archs added in your PR from earlier: https://github.com/milesgranger/pyrus-cramjam/pull/54

In a [separate build for cramjam](https://travis-ci.com/github/conda-forge/cramjam-feedstock/jobs/504863395#L546) I'm getting a `cramjam-2.3.0-cp37-cp37m-manylinux_2_24_ppc64le.whl is not a supported wheel on this platform.` Note that this build for conda is merely just installing the wheels from PyPi.

When I look at a project like [`retworkx`](https://pypi.org/project/retworkx/#files) their ppc64le is formatted like `retworkx-0.8.0-cp36-cp36m-manylinux2014_ppc64le.whl `
where mine is `cramjam-2.3.0-cp36-cp36m-manylinux_2_24_ppc64le.whl`

Makes me believe the naming is all that is off. What do you think?

Ref: https://github.com/conda-forge/cramjam-feedstock/pull/14

**Comment by messense** [comment]
It's `manylinux_2_24` because I can't build a `manylinux2014` compatible docker image for cross compiling. `retworkx` builds ppc64le with QEMU so it can use `manylinux2014` but it's really slow to build.

**Comment by messense** [comment]
You can try running `pip debug --verbose` to dump compatible tags.

**Comment by messense** [comment]
https://anaconda.org/conda-forge/pip

![image](https://user-images.githubusercontent.com/1556054/118006115-92cb1a00-b37d-11eb-824b-28a1dffa7438.png)

It seems the pip version on conda-forge for linux/ppc64le platform is v20.0.2? I think `manylinux_2_24` tag needs pip v20.1

**Comment by milesgranger** [comment]
Good find! 

But it seems in general installing from PyPi/pip was frowned upon, so I think they're going to try and make it work the "conda way". If it comes to trying to re-use the wheels from PyPi I'll definitely give this a go!

Thanks for the help! :-)

**Comment by messense** [comment]
Good news! I've managed to [build an manylinux2014 ppc64le docker image for cross compiling](https://github.com/messense/manylinux-cross/commit/df049e73fc85f3bcdf9d8a5bacab6fb420230361), the hard part was getting GLIBC 2.17 compile. Should be available soon in maturin-action.

**Comment by milesgranger** [comment]
Oi! What a legend, that is awesome! :open_mouth: :raised_hands:

**Comment by messense** [comment]
It's available now. You can simply re-run the release workflow to use it.

**Comment by milesgranger** [comment]
Doing that now, thanks again!

**Comment by messense** [comment]
Note that the wheel name was changed to [include PEP 600 alias](https://github.com/pypa/auditwheel/pull/288): `cramjam-2.3.0-cp39-cp39-manylinux_2_17_ppc64le.manylinux2014_ppc64le.whl`

**Comment by milesgranger** [comment]
ah just was looking into that as the naming looked a bit different than I'm used to, thanks for clarifying that. :-)
